library(tidyverse)
library(anomalize)
library(zoo)
library(tibble)
sub_serie <- subset(SeriesIniciar, select = -c(Tipo,Serie))
serie <- unname(unlist(sub_serie[1,]))
serie <- serie[!is.na(serie)]
serie <- ts(serie, start=c(2000, 1), frequency=12)
serie <- data.frame(Y=as.matrix(serie), date=as.Date(as.yearmon(time(serie))))
serie <- as_tibble(serie)
print(serie)
test <- time_decompose(serie, target = Y, method = "twitter")
test <- anomalize(test, target = remainder, method = "iqr")
time_recompose(test)
print(test)
plot(cars)