r = getOption("repos")
r["CRAN"] = "http://cran.us.r-project.org"
options(repos = r)

install.packages('nortest')
install.packages('stats')
install.packages('liftLRD')
install.packages('pracma')
#install.packages('fractal')
install.packages('tsfeatures')
install.packages('tseries')
install.packages('longmemo')
install.packages('PerformanceAnalytics')
install.packages('WeightedPortTest')
install.packages('fractaldim')
install.packages('TSEntropies')
install.packages('ForeCA')
install.packages('pracma')
install.packages('anomalize')
install.packages('tidyverse')
install.packages('wavelets')
#devtools::install_github("hendersontrent/catch22")


source("nortest.R")
source("stats.R")
source("lift.R")
# source("Catch22.R")
source("pracma.R")
#source("fractal.R")
source("tsfeatures.R")
source("tseries.R")
source("longmemo.R")
source("PerformanceAnalytics.R")


Train <- read.csv("~/MetaLearning/Asistencia/FeaturesR/Train.csv", header=T)
head(Train)
file <- list(Train)


nortest_generator(file)
stats_generator(file)
lift_generator(file)
#catch22_generator(file)
pracma_generator(file)
#fractal_generator(file)
tsFeatures_generator(file)
tseries_generator(file)
longmemo_generator(file)
performance_analytics_generator(file)
